# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-25 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '0004_auto_20190524_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=40)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('town_or_city', models.CharField(max_length=50)),
                ('street_address1', models.CharField(max_length=50)),
                ('street_address2', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.localtime, editable=False)),
                ('total_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField(editable=False)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Features')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.Order')),
            ],
        ),
    ]
