# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_features_paid_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='features',
            old_name='paid_by',
            new_name='paid_no',
        ),
    ]
