# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_auto_20190524_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featurecomment',
            old_name='bug',
            new_name='feature',
        ),
    ]
