# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_auto_20190524_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='features',
            old_name='paid_no',
            new_name='total_votes',
        ),
    ]
