# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 22:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_bugs_voted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='voted_by',
            field=models.ManyToManyField(related_name='voted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
