# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0005_auto_20190523_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugs',
            name='published',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
