# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0007_bugcomment_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugcomment',
            name='published',
            field=models.DateField(default=django.utils.timezone.localtime, editable=False),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='published',
            field=models.DateField(default=django.utils.timezone.localtime, editable=False),
        ),
    ]
