# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 09:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0008_auto_20190524_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='voted_by',
            field=models.ManyToManyField(blank=True, related_name='voted', to=settings.AUTH_USER_MODEL),
        ),
    ]
