# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0010_auto_20190524_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugs',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
